name: Newsletter
favicon: null
layout_spectrum: 0.75361
typography_spectrum: 0.36057676328346133
title: "News created and for SpritTech's"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#401b01'
    - '#d86c24'
    - '#fff6ef'
    - '#ac4300'
    - '#b08b74'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
